export default [
  "Sewing",
  "Cleaning",
  "Welding",
  "Auto Repairs",
  "Beauty and Fashion",
  "Laundry and Cleaning",
  "Home or Office",
  "Electrical Electronics and Appliances",
  "Building Mechanical and Fabrication",
  "Event Planning",
  "Computer Mobile and IT",
  "Educational",
  "Real Estate",
  "Transportation services",
  "Entertainment",
  "Medical and Legal",
  "Business",
  "Farming and Agriculture",
  "Other Services"
]